### ISSUE TITLE
build 92 and java 6

### ISSUE THREAD

**Issue by leslem** [delt0r/msms#17]
The latest build of msms appears to fail under Java 6. I've tried it in two environments, as described below.

On a Mac Pro running OS X 10.6.8 and Java version 1.6.0_45, I get the following error when invoking msms -version:
Exception in thread "main" java.lang.UnsupportedClassVersionError: at/MSLike : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
    at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)

On a compute cluster running Red Hat Enterprise Linux Server 6.2 and using a module for Java 6u35, I get the a similar error when invoking msms -version:
Exception in thread "main" java.lang.UnsupportedClassVersionError: at/MSLike : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(Unknown Source)
    at java.lang.ClassLoader.defineClass(Unknown Source)
    at java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.defineClass(Unknown Source)
    at java.net.URLClassLoader.access$000(Unknown Source)
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)

But, on the same compute cluster, if I use the Java 7u17 module instead, msms -version works, as does a simple test case for simulations (msms 5 10 -t 3.0)

**Comment by leslem** [comment]
I've replicated this problem on a MacBook Pro running Lion (10.7.5) and java version 1.6.0_45. 

Furthermore, it appears that there is no officially sanctioned way to install java 7 on OS X 10.6.8 (still the most widely used Mac OS).

**Comment by delt0r** [comment]
Recompiled for java 6. However support for 6 will be phased out soon.

**Comment by leslem** [comment]
Sorry, but I'm still getting the same error with the new version downloaded from the msms website an hour ago. I looked into compiling it from source myself, but the readme.txt & build.xml files and ant subdirectory referenced in the manual are nowhere to be found.

**Comment by delt0r** [comment]
Yes. I found the root of the problem. Some of my branches are 1.7 only and
i have merged them. So early in the day you would have got 1.6, later 1.7.
This is now fixed. But please note that support for 1.6 will be dropped
soon.

Also the place to get all the source etc is github.

On Wed, May 29, 2013 at 8:46 PM, emeryl notifications@github.com wrote:

> Sorry, but I'm still getting the same error with the new version
> downloaded from the msms website an hour ago. I looked into compiling it
> from source myself, but the readme.txt & build.xml files and ant
> subdirectory referenced in the manual are nowhere to be found.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/delt0r/msms/issues/17#issuecomment-18637662
> .

## 

I have no special talents. I am only passionately curious.
--Albert Einstein

**Comment by delt0r** [comment]
Also I should state that you should use the build number for bug reporting.
I update the website frequently during bugfixing days, and this makes it
easier to track down mistakes.

On Thu, May 30, 2013 at 9:20 AM, Greg Ewing greg.ewing@gmail.com wrote:

> Yes. I found the root of the problem. Some of my branches are 1.7 only and
> i have merged them. So early in the day you would have got 1.6, later 1.7.
> This is now fixed. But please note that support for 1.6 will be dropped
> soon.
> 
> Also the place to get all the source etc is github.
> 
> On Wed, May 29, 2013 at 8:46 PM, emeryl notifications@github.com wrote:
> 
> > Sorry, but I'm still getting the same error with the new version
> > downloaded from the msms website an hour ago. I looked into compiling it
> > from source myself, but the readme.txt & build.xml files and ant
> > subdirectory referenced in the manual are nowhere to be found.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/delt0r/msms/issues/17#issuecomment-18637662
> > .
> 
> ## 
> 
> I have no special talents. I am only passionately curious.
> --Albert Einstein

## 

I have no special talents. I am only passionately curious.
--Albert Einstein
