### ISSUE TITLE
Example from manual fails

### ISSUE THREAD

**Issue by szpiech** [delt0r/msms#35]
Hello,  I've tried to run the example command from the manual (pg. 17 section 7.1, after correcting a typo `-en 0.2 .5` to `-en 0.2 1 .5`).

```
./msms -N 10000 -ms 80 1 -I 4 20 20 20 20 0 -t 100 -r 100 1000 -es 0 3 .5 -ej 0 4 5 -g 2 10 -g 3 100 -g 5 200 -n 2 .0 -n 3 2 -n 5 11 -m 1 3 5 -m 3 1 5 -m 1 2 2 -m 2 1 2 -ej 0.04 5 3 -ej 0.05 3 2 -en 0.05 2 .5 -em 0.05 1 2 12 -em 0.05 2 1 12 -ej 0.15 2 1 -en 0.2 1 .5 -SI 0.05 5 0 0 0 0 0 -Sc 0 3 100 50 0 -Smu 0.1
```

I receive the following error.

```
ms -N 10000 80 1 -I 4 20 20 20 20 0 -t 100 -r 100 1000 -es 0 3 .5 -ej 0 4 5 -g 2 10 -g 3 100 -g 5 200 -n 2 .0 -n 3 2 -n 5 11 -m 1 3 5 -m 3 1 5 -m 1 2 2 -m 2 1 2 -ej 0.04 5 3 -ej 0.05 3 2 -en 0.05 2 .5 -em 0.05 1 2 12 -em 0.05 2 1 12 -ej 0.15 2 1 -en 0.2 1 .5 -SI 0.05 5 0 0 0 0 0 -Sc 0 3 100 50 0 -Smu 0.1  [3.2rc Build:123]
0x25e1e7d06dd811f

Exception in thread "main" java.lang.RuntimeException: Argument p is NaN!
    at cern.jet.random.Binomial.generateBinomial(Binomial.java:143)
    at at.mabs.model.selection.DefaultSelectionSimulator.selectionSimulationStep(DefaultSelectionSimulator.java:416)
    at at.mabs.model.selection.DefaultSelectionSimulator.forwardSimulator(DefaultSelectionSimulator.java:324)
    at at.mabs.model.selection.SelectionData.runSelectionSimulation(SelectionData.java:195)
    at at.mabs.model.ModelHistroy.simulateSelection(ModelHistroy.java:380)
    at at.MSLike.run(MSLike.java:299)
    at at.MSLike.runThreads(MSLike.java:424)
    at at.MSLike.runMe(MSLike.java:191)
    at at.MSLike.main(MSLike.java:543)
    at at.MSLike.main(MSLike.java:587)
```

**Comment by delt0r** [comment]
Next release should fix this. The mistake in the manual will be fix in the new manual... which is not ready yet.
