### ISSUE TITLE
Using -SI at time 0 produces NullPointerException

### ISSUE THREAD

**Issue by paulstaab** [delt0r/msms#40]
When starting selection at time `0` msms throws a `NullPointerException`:

``` bash
msms 5 1 -SI 0.0 1 5e-04 -SAA 1000 -SAa 500 -N 10000
ms 5 1 -SI 0.0 1 5e-04 -SAA 1000 -SAa 500 -N 10000  [3.2rc Build:162]
0x71f3c4584961bf28

Exception in thread "main" java.lang.NullPointerException
        at at.mabs.model.selection.DefaultSelectionSimulator.forwardSimulator(DefaultSelectionSimulator.java:281)
        at at.mabs.model.selection.SelectionData.runSelectionSimulation(SelectionData.java:195)
        at at.mabs.model.ModelHistroy.simulateSelection(ModelHistroy.java:381)
        at at.MSLike.run(MSLike.java:299)
        at at.MSLike.runThreads(MSLike.java:424)
        at at.MSLike.runMe(MSLike.java:191)
        at at.MSLike.main(MSLike.java:543)
        at at.MSLike.main(MSLike.java:587)
```

Doing this makes no sense at all, but I wanted to let you know in case you want to add a more informative error message (or just do what the user asks for and ignore the command...).

**Comment by delt0r** [comment]
Thanks. Will look into it.

**Comment by delt0r** [comment]
Thanks. Will look into it.
