### ISSUE TITLE
Second example from quickstart page fails

### ISSUE THREAD

**Issue by winni2k** [delt0r/msms#51]
The second example (Adding selection) from the [quickstart](https://www.mabs.at/ewing/msms/quickStart.shtml) web page fails on my machine. The command in question is `msms -N 10000 -ms 10 1000 -t 1 -SAA 100 -Sa 50 -SF 0`. The error I get is:

```bash
msms/bin/msms -N 10000 -ms 10 1000 -t 1 -SAA 100 -Sa 50 -SF 0
-SAA has an incorrect number of arguments. [100, -Sa, 50]
options you tried was:
-SAA 100 -Sa 50
Option help:
-SAA double
	The selection strength of the Homozygote derived type, alpha=2*N*s


at.mabs.cmdline.CmdLineParseException: -SAA has an incorrect number of arguments. [100, -Sa, 50]
	at at.mabs.cmdline.CmdLineParser$DelimitedArgs.<init>(CmdLineParser.java:393)
	at at.mabs.cmdline.CmdLineParser.processArguments(CmdLineParser.java:128)
	at at.MSLike.updateParser(MSLike.java:215)
	at at.MSLike.<init>(MSLike.java:121)
	at at.MSLike.main(MSLike.java:542)
	at at.MSLike.main(MSLike.java:587)
```

These are the steps I took to generate this error:

```bash
wget https://www.mabs.at/ewing/msms/msms3.2rc-b163.zip
unzip msms3.2rc-b163.zip
chmod +x msms/bin/msms

msms/bin/msms -N 10000 -ms 10 1000 -t 1 -SAA 100 -Sa 50 -SF 0
```

**Comment by winni2k** [comment]
It looks like there is a typo on the quickstart web page. The argument `-Sa` does not appear to be a valid argument. It looks like replacing `-Sa` with `-SAa` works.
